### PR TITLE
Fix the tag finding

### PR DESCRIPTION
**Pull request by ErjanGavalji**

### CODE REVIEW

**Comment by skywinder** [comment]
Thanks for PR, But I already implement it and fix this bug (and tests also). I will release new version today

**Comment by skywinder** [comment]
Fixed in 6fdcc0c

**Comment by skywinder** [comment]
@ErjanGavalji anyway, much appreciated. Thanks! :+1:

**Comment by ErjanGavalji** [comment]
! perfect !

**Pull request closed without merging**
