### PR TITLE
Add compare link between older version and newer version

### PR DESCRIPTION
**Pull request by sue445**
I was inspired to rspec changelog

https://github.com/rspec/rspec-core/blob/master/Changelog.md

# Example
https://github.com/sue445/Github-Changelog-Generator/blob/eb9bd59f261812d0e13032bd6393c18d5a89251d/CHANGELOG.md

### CODE REVIEW

**Comment by skywinder** [comment]
Nice feature, thanks! 
Please add a key to [parser.rb](https://github.com/skywinder/Github-Changelog-Generator/blob/master/lib/github_changelog_generator/parser.rb) to have ability enable/disable this option (you can set it enable by default).

**Comment by sue445** [comment]
@skywinder ok. I added option `--[no-]compare-link` at 1fced72

**Comment by skywinder** [comment]
Great! Thanks for contribution!

**Comment by sue445** [comment]
:smile_cat:

**Comment by skywinder** [comment]
@sue445 Already in `1.2.7` with your name in CHANGEOG :wink:

**Pull request merged**
