### PR TITLE
Git Subcommand

### PR DESCRIPTION
**Pull request by dlanileonardo**
#255  Just symlink to main bin to create git subcommand.

@skywinder Are you think? I use symlink copy bin, or simple call github_changelog_generator?

You can use ```git generate-changelog```

~~The problem: You cant use --help only -h.~~

~~I can use  the example @Natim https://github.com/tj/git-extras ?~~

### CODE REVIEW

**Comment by dlanileonardo** [comment]
- [ ] Fill help man with all params

**Comment by skywinder** [comment]
@dlanileonardo Great work! About man page, here a tutorial: https://github.com/tj/git-extras/tree/master/man how to create man pages.
I will try to implement it soon.

**Comment by skywinder** [comment]
@dlanileonardo Awesome. It works like a charm!
Done, please merge my PR to add my changes with man page and params description.

**Comment by skywinder** [comment]
1. But I can't figure out, what command should present this man page, that we generated?

    > git help generate-changelog
     No manual entry for git-generate-changelog

2. It's needed to specify about this feature in readme.md before merge

**Comment by dlanileonardo** [comment]
Thanks! @skywinder to show this man page is ```git generate-changelog --help```.

Yes i will put in README.md an info about this.

**Comment by skywinder** [comment]
@dlanileonardo got `No manual entry for git-generate-changelog` return for `git generate-changelog --help` command also..

**Comment by dlanileonardo** [comment]
I'm Sorry :scream:, i change de default task in Rakefile to run script after install and tests, because this is default native in rake_builder. In travis i put checks tasks to run rubocop and rspec. Itz Ok? :sweat_smile:

**Comment by dlanileonardo** [comment]
@olleolleolle Okay! Done! @skywinder 

What think about i'll make autcomplete bash?

**Comment by skywinder** [comment]
@dlanileonardo it's awesome! Especially thanks to 3bc1e9b, since I'm not familiar with Rake as you!

> What think about i'll make autcomplete bash?

It would be awesome! :+1:

**Comment by olleolleolle** [comment]
Hello again! I took a look at this PR again, it's still shiny and all.

It made me think. 

When we've merged this, we'll want to keep the man page artifacts up-to-date.

Then, it'd be nice if the project's options were discoverable and renderable from a script, which could feed something like [pandoc](http://pandoc.org/demos.html) to create all the necessary files (.1, .md, .html, et cetera).

So, :hammer: 

- keeping the command-line, Rake, and direct-into-constructor options together, somehow
- being able to access them (as structured data) to be able to feed them to a docs generation system

**Comment by skywinder** [comment]
> @dlanileonardo  What think about i'll make autcomplete bash?

This will fix #255

**Comment by dlanileonardo** [comment]
Done! @skywinder, im sorry for the delay.

**Comment by skywinder** [comment]
@dlanileonardo thanks. Can you advise, how to automatically generate .1, .md, .html files for man pages?

**Comment by skywinder** [comment]
btw, It would be nice to mentio about new feature in readme also

**Pull request merged**
