### PR TITLE
Use octokit, carrying awaage commits

### PR DESCRIPTION
**Pull request by olleolleolle**
This is a rebased PR of this collection of changesets by @awaage:

- #381 Use OctoKit
- #382 Cache OctoKit GH requests
- #384 Replace Fetcher with OctoFetcher  
- #387 Tags handled differently

The goal is to have an **OctoKit**-based metadata fetching.

By using the Faraday-based OctoKit, we now have [VCR](https://relishapp.com/vcr/vcr/docs) support in the test suite, as well.

This PR represents the work of the Project card https://github.com/skywinder/github-changelog-generator/projects/1#card-278430

### CODE REVIEW

**Comment by awaage** [comment]
Thanks @olleolleolle ! This is great!

**Comment by awaage** [comment]
From this point, what else do we need? How do you plan to release this?

**Comment by olleolleolle** [comment]
Did the public API change? If yes, I think we must bump the major version.

Do we stand to gain anything by keeping up a 1.x release series around? (Perhaps the freedom to innovate in the 2.x and cut off old platforms?) A way to have the possibility to release patch fixes to 1.x versions. 

@skywinder Any thoughts/reactions? I'm curious to hear your ideas and hopes. Did you see the Project in the Github site? The one where I ask us to find an interface that a backend like OctoFetcher can implement. Would it enable a Gitlab user to build their own Fetcher, supporting other ways of providing data for the generator? 

Thanks for participating in all this.

**Comment by olleolleolle** [comment]
Let's move this forward!

**Comment by skywinder** [comment]
@olleolleolle That's pretty interesting idea with OctoFetcher! It would be amazing to extend all of this algorithms for Bitbucket too. I will think about that.

And in addition to my personal email:

As for me is very important to see, how the project is rising. 
And it could be real only your effort! 
Thank you very much for the help! 👍

**Comment by olleolleolle** [comment]
Thank you for the trust and encouragement.

**Pull request merged**
