### PR TITLE
Remove --between-tags option

### PR DESCRIPTION
**Pull request by Lucashuang0802**

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
@olleolleolle I bet you are interested in collaborating with me on this one?

**Comment by olleolleolle** [comment]
Hello!

The metadata of a change is quite important to this project. 

A description which explains how something is wrong and what has been done to right it and why this all matters to a user. That's part of communicating your intent to others who wonder. 

Can you find and link to any discussion which weighs the issue somewhere?

I'm sure there's context to this somewhere, but I can't find it from this PR.

**Comment by Lucashuang0802** [comment]
There you go: #450 @olleolleolle

**Comment by olleolleolle** [comment]
Thank you for this PR!

**Comment by Lucashuang0802** [comment]
@olleolleolle I guess there are some post-development to do for this removal. Let me see what I could find out!

**Comment by hunner** [comment]
@olleolleolle @Lucashuang0802 Is this change a bugfix or a breaking change? If the latter, then the next version of GCG will be v2.0.0 to account for this, yeah?

**Pull request merged**
