### PR TITLE
Use GitHub tags to reference GitHub users

### PR DESCRIPTION
**Pull request by phase**
This will use @tags to notify the contributor that their contribution is in the changelog.

As discussed in https://github.com/github/linguist/pull/2698#issuecomment-150887871

### CODE REVIEW

**Comment by olleolleolle** [comment]
Cool feature! Thanks for proposing it as code!

I think of it as a short-form, GitHub-only Markdown optimization.

I tried extracting user presentation to its own method https://gist.github.com/olleolleolle/218060ffe29017d7d9f1 - which avoided any Rubocoply warnings - but changed no behavior. This can then be a site for any future option-querying of settings like `@options["usernames_as_github_logins"]`.

**Comment by phase** [comment]
@olleolleolle Should be good to go!

**Comment by olleolleolle** [comment]
- Before this change, links to user profiles would work anywhere Markdown could be generated
- This PR introduces a slight change of behavior – favouring rendering on GitHub over "anywhere Markdown can be rendered"

If @skywinder finds the "render username as a link anywhere" functionality useful enough to keep, we may need to introduce a user-configurable option.

**Comment by skywinder** [comment]
Agree with @olleolleolle about user-configurable option. 
The feature make change log a quite shorter, but we lose ability to follow by user's link anywhere but GitHub page.
I agree to add this feature as option that disabled by default (to save backward compatibility). `@options["usernames_as_github_logins"]` seems clear to understand.

**Comment by phase** [comment]
Maybe something like `tag_github_users`. How would I implement this as an option?

**Comment by olleolleolle** [comment]
@phase There are a few ways of specifying options

- rake options
- CLI options

Here is the OptionParser-based CLI option parsing, where you can introduce `usernames_as_github_logins`

https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/parser.rb#L39

**Comment by olleolleolle** [comment]
And, the Rake task options are picked up here: https://github.com/skywinder/github-changelog-generator/blob/master/lib/github_changelog_generator/task.rb#L9

**Comment by phase** [comment]
Something like that? (I will add a check for it in a second)

**Comment by olleolleolle** [comment]
We want to inform the user of what the option does ("recommended for rendering on GitHub" vs "recommended for rendering anywhere") and what the default value is.

**Comment by skywinder** [comment]
@phase are you going to finish this PR? Seems `usernames-as-github-logins` not binded to new option yet.

**Comment by olleolleolle** [comment]
Closing this issue, carried in PR #301.

**Pull request closed without merging**
