### PR TITLE
Do not alter pull_requests while iterating on it

### PR DESCRIPTION
**Pull request by raphink**
Deleting elements of an array while iterating on it
results in never seeing the last element.

    > a = [1,2,3]
     => [1, 2, 3]
    > a.each do |e|
    >   p a
    >   a.delete(e)
    > end
    [1, 2, 3]
    [2, 3]
     => [2]

### CODE REVIEW

**Comment by raphink** [comment]
@skywinder all builds are currently failing on the master branch, I'm willing to rebase once they pass.

**Comment by skywinder** [comment]
@raphink Great attention to details. Thank you again! Can't understand, why build start failing.
But your code as absolutely correct, so I will merge it now!

**Comment by skywinder** [comment]
btw: @raphink You help me a lot with  cool enhancements and your code always is very clean. Thanks again. :+1: 
May I propose  to add you to a Collaborators to this project?

**Comment by raphink** [comment]
Just one more project to watch for, that can't hurt ;-)

**Comment by raphink** [comment]
Fancy a patch release @skywinder ?

**Comment by skywinder** [comment]
I thought that can fix some other this soon, but don't have a time.
So `1.8.3` released, thanks!

**Comment by raphink** [comment]
Thank you!

**Pull request merged**
