### PR TITLE
Use closed_at and merged_at when filtering issues/prs

### LINKED ISSUE #503: PR cited in the wrong TAG
I am not sure if this is related to #491 but we have a specific case (private repo, sorry) where a PR is cited in the wrong TAG.

I think it has to do with method `filter_issues_for_tags` using `actual_date`. I'm working on a PR ;-)

### PR DESCRIPTION
**Pull request by unicolet**
Fixes #503 in my tests with our private repo.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Hi! Glad you took the time to make a PR!

In order to explain what it does, can we add a test of some kind that proves/explains how merged_at and closed_at are the field we wish to use?

**Comment by olleolleolle** [comment]
Maybe all it takes is a bit of documentation in the code, as docstrings ([YARD](http://yardoc.org/)) for this method?

**Comment by unicolet** [comment]
@olleolleolle would that work?

**Comment by unicolet** [comment]
@olleolleolle let me know if there is anything else that you want me to do here. Thanks :smile:

**Comment by unicolet** [comment]
@olleolleolle merged PR with master, Travis is green again :-)

**Comment by unicolet** [comment]
since apologies for the noise, I clicked on the wrong button

**Comment by alexjfisher** [comment]
@olleolleolle Any chance of getting this merged?  We've bumped into the same issue on https://github.com/voxpupuli/puppet-rabbitmq. @wyardley Could you link to your branch that demonstrates this issue?

**Comment by alexjfisher** [comment]
@olleolleolle Thanks!

**Pull request merged**
