### PR TITLE
Original Fetcher removed and rubocop passes

### PR DESCRIPTION
**Pull request by awaage**
Two things:
1. Original Fetcher removed 
2. rubocop passes

This PR was branched off of (https://github.com/skywinder/github-changelog-generator/pull/381) 

So it doesn't clutter the changeset of (https://github.com/skywinder/github-changelog-generator/pull/381)

This current PR is the FULL changeset, inclusive of #381.

My advice is to review changeset of #381 first, and then instead of merging that one, just merge This one (#384) which will handle test passing / rubocop passing / removing original Fetcher.

Hope that makes sense.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Aw! Since I was not reading _everything_, I missed the existence of this PR.

I should make https://github.com/retentionscience/github-changelog-generator/pull/1 on top of this one, if any changes of mine are even necessary.

**Comment by skywinder** [comment]
@awaage #392 brokes your PR. But it's almost nothing t change, merge in manual mode works fine. Please merge `master` to you branch. Please, let me know, If you need help - I can create PR to your repo.

**Comment by olleolleolle** [comment]
Oh, hello: I'm wondering if you're up to making https://github.com/retentionscience/github-changelog-generator/tree/aw/all-merged the OctoKit PR to rule them all?

**Comment by awaage** [comment]
@olleolleolle Sorry, I have left this so long. 

I did create all-merged to combine the (https://github.com/skywinder/github-changelog-generator/pull/387) with (https://github.com/skywinder/github-changelog-generator/pull/384). 

I didn't want to confuse by adding another PR until the previous two are accepted. 

Do you want me to create another PR with all-merged?

**Comment by olleolleolle** [comment]
@awaage Yes, I would prefer a PR with the "all-merged" version.

I now see that you've merged my PR on top of _that_ branch. Great. A PR for that, and we can move on from there.

**Comment by skywinder** [comment]
You are awesome, guys. Can't expain, how I grateful for that! 👍

**Comment by olleolleolle** [comment]
Duplicate of #422.  Closing this issue. Thank you!

**Pull request closed without merging**
