### PR TITLE
AppVeyor: drop init build hook, add .gitattributes instead

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR introduces `.gitattributes` to avoid extra steps in AppVeyor CI configuration file.

Read more: [Git Book about gitattributes](https://git-scm.com/docs/gitattributes)

### CODE REVIEW

**Comment by olleolleolle** [comment]
Oh, like this, @Arcanemagus?

**Comment by Arcanemagus** [comment]
Yep, that should do it 😉.

Note that if you ever add a binary mode file (eg. an image) to the repo it will need to be specified in here as binary or it could get mangled on checking out/in.

**Comment by olleolleolle** [comment]
@Arcanemagus I'm sad to say that I failed to get this to work in AppVeyor.

```
Gemfile:1:1: C: Layout/EndOfLine: Carriage return character missing. (https://github.com/bbatsov/ruby-style-guide#crlf)
# frozen_string_literal: true ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
github_changelog_generator.gemspec:1:1: C: Layout/EndOfLine: Carriage return character missing. (https://github.com/bbatsov/ruby-style-guide#crlf)

```

**Comment by olleolleolle** [comment]
@Arcanemagus And, isn't taking care not to mangle non-text files, isn't that a chore?

**Comment by Arcanemagus** [comment]
> I'm sad to say that I failed to get this to work in AppVeyor.

Sorry about that! I thought you were trying to standardize on a line ending, forgetting that your specs depend on the OS running them.

> And, isn't taking care not to mangle non-text files, isn't that a chore?

Yes, but consistency across all machines (when that is what you want) is generally worth the minor additional work required to maintain that from what I've found.

**Pull request merged**
