### PR TITLE
Parser: YARD docstrings and a rename, and RegExp named capture groups

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR improves **documentation** and very small refactoring: **extract two RegExps**, and give their capture groups labels.

While reading the code, I noted that there were a few additional methods that had quite little documentation. While documenting, I named a few variables.

Interested parties can use YARD to generate documentation.

### CODE REVIEW

**Comment by olleolleolle** [comment]
(That build failure is rack 2.x demanding 2.2+ of Ruby to work.)

**Comment by skywinder** [comment]
@olleolleolle Perfect, as usual :)
Seems, there is no limitation about upper version of ruby. But have to check.
Can you bump ruby version in `.travis.yml` in order to make travis works?

**Comment by olleolleolle** [comment]
If-and-when we get rid of the Rack dependency, we'd be able to ignore that bit, and be compatible farther down the EOL chain of Rubies.

BUT, we could also make a definitive call and say "the project supports stable-and-not-EOL'd Rubies".

**Comment by skywinder** [comment]
@olleolleolle The only reason to don't do that - is support of old versions of ruby, am I right? 
Is so, I don't mind in support of outdated versions of ruby. So, let's do this. 
We can bump major number with this  move. So, anyone, who want to use this project - can stay on `1.x`. Versions.

**Comment by olleolleolle** [comment]
@skywinder This PR does not belong in the 2.0.0 milestone. If you review the code changes in this PR, you can see nothing in this changed dependencies.

**Pull request merged**
