### PR TITLE
README: Documentation update about RakeTask params and how to translate labels

### PR DESCRIPTION
**Pull request by edusantana**
I have put the word 'translate' because it helps to find the idea.

### CODE REVIEW

**Comment by edusantana** [comment]
@olleolleolle done.

**Comment by olleolleolle** [comment]
Super!

**Comment by olleolleolle** [comment]
Now that this is a PR, and it will be a line in the generated changelog - if we want it to - the title becomes important. 

Can you rename this PR so that its title can represent and explain it as a single line of changelog?

Alternatively: do you want it to have a Github Label that we will exclude from the generated changelog. 

Your call.

**Comment by edusantana** [comment]
@olleolleolle I think its fine now.

**Comment by olleolleolle** [comment]
Thank you!

**Pull request merged**
