### PR TITLE
Add options to def self.user_and_project_from_git to fix parser.rb:19…

### PR DESCRIPTION
**Pull request by SteveGilvarry**
…3 wrong number of arguments (1 for 0)

Calling user_and_project_from_git(options) but was defined without options param.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Thank you, Steve!

**Comment by SteveGilvarry** [comment]
@olleolleolle Travis failed?

**Comment by olleolleolle** [comment]
There was a technical error about fetching gems, which had nothing to do with your change.

**Comment by SteveGilvarry** [comment]
OK thanks.

**Pull request merged**
